sender_email: vaibhavphalke1950@gmail.com
saved_senders_list:
- vaibhavphalke1950@gmail.com
recipients:
- vaibhav.phalke@infrabeat.com
cc_recipients:
- vishal.sarode@infrabeat.com
- om.dighe@infrabeat.com
